/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocoloco;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author bullock.brandon
 */
public class updateProviders extends javax.swing.JFrame {

    /**
     * Creates new form updateProviders
     */
    public updateProviders() {
        initComponents();
    }
    public updateProviders(String a, String b, String c, String d, String e, String f) {
        initComponents();
        
        providerIDBox.setText(a);
        providerNameBox.setText(b);
        providerAddressBox.setText(c);
        providerCityBox.setText(d);
        providerStateBox.setSelectedItem(e);
        providerZipBox.setText(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providerZipBox = new javax.swing.JTextField();
        jLabelmName = new javax.swing.JLabel();
        jLabelmState = new javax.swing.JLabel();
        providerNameBox = new javax.swing.JTextField();
        jLabelmID = new javax.swing.JLabel();
        jLabelmZip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelmStreet = new javax.swing.JLabel();
        providerCityBox = new javax.swing.JTextField();
        system_name = new javax.swing.JLabel();
        providerStateBox = new javax.swing.JComboBox<>();
        providerAddressBox = new javax.swing.JTextField();
        jBtnBack = new javax.swing.JButton();
        providerIDBox = new javax.swing.JTextField();
        confirmUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelmName.setText("  Name:");
        jLabelmName.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelmName.setMinimumSize(new java.awt.Dimension(60, 70));

        jLabelmState.setText(" State:");
        jLabelmState.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelmState.setMinimumSize(new java.awt.Dimension(60, 70));

        providerNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerNameBoxActionPerformed(evt);
            }
        });

        jLabelmID.setText("Provider ID:");
        jLabelmID.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelmID.setMinimumSize(new java.awt.Dimension(60, 70));

        jLabelmZip.setText("Zip Code:");
        jLabelmZip.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelmZip.setMinimumSize(new java.awt.Dimension(60, 70));

        jLabel1.setText("City:");

        jLabelmStreet.setText("Address:");
        jLabelmStreet.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabelmStreet.setMinimumSize(new java.awt.Dimension(60, 70));

        system_name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        system_name.setText("ChocAn Information System");

        providerStateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));

        providerAddressBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerAddressBoxActionPerformed(evt);
            }
        });

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        providerIDBox.setEnabled(false);
        providerIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerIDBoxActionPerformed(evt);
            }
        });

        confirmUpdate.setText("Confirm Update");
        confirmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(system_name)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(confirmUpdate)
                        .addGap(45, 45, 45)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(providerCityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelmState, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(providerStateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelmZip, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(providerZipBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelmStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(providerIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(providerNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(providerAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(117, 117, 117))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(system_name)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelmZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerZipBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(providerCityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerStateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBack)
                    .addComponent(confirmUpdate))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void providerNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerNameBoxActionPerformed

    private void providerAddressBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerAddressBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerAddressBoxActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chocoloco", "brandonbullock", "borderlands");

            String getData = "select * from providers where providerID = ?";
            PreparedStatement pstmt = conn.prepareStatement(getData);
            pstmt.setInt(1, Integer.parseInt(providerIDBox.getText()));

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()){
                String providerID = rs.getString("providerID");
                String providerName = rs.getString("providerName");
                String providerAddress = rs.getString("providerAddress");
                String providerCity = rs.getString("providerCity");
                String providerState = rs.getString ("providerState");
                String providerZip = rs.getString("providerZip");

                new viewProviders(providerID, providerName, providerAddress, providerCity, providerState, providerZip).setVisible(true);
                this.dispose();

            } else JOptionPane.showMessageDialog(null, "Provider not found!");

            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void providerIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerIDBoxActionPerformed

    private void confirmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUpdateActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chocoloco", "brandonbullock", "borderlands");

            String updateData = "update providers set providerName = ?, providerAddress = ?, providerCity = ?, providerState = ?, providerZip = ? where providerID = ?";
            PreparedStatement pstmt = conn.prepareStatement(updateData);
            pstmt.setString(1, providerNameBox.getText());
            pstmt.setString(2, providerAddressBox.getText());
            pstmt.setString(3, providerCityBox.getText());
            pstmt.setString(4, providerStateBox.getSelectedItem().toString());
            pstmt.setInt(5, Integer.parseInt(providerZipBox.getText()));
            pstmt.setInt(6, Integer.parseInt(providerIDBox.getText()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Provider Updated");
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_confirmUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateProviders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmUpdate;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelmID;
    private javax.swing.JLabel jLabelmName;
    private javax.swing.JLabel jLabelmState;
    private javax.swing.JLabel jLabelmStreet;
    private javax.swing.JLabel jLabelmZip;
    private javax.swing.JTextField providerAddressBox;
    private javax.swing.JTextField providerCityBox;
    private javax.swing.JTextField providerIDBox;
    private javax.swing.JTextField providerNameBox;
    private javax.swing.JComboBox<String> providerStateBox;
    private javax.swing.JTextField providerZipBox;
    private javax.swing.JLabel system_name;
    // End of variables declaration//GEN-END:variables
}
