/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocoloco;

import com.github.lgooddatepicker.components.DatePicker;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ispre
 */
public class VisitDetails extends javax.swing.JFrame {

    /**
     * Creates new form VisitDetails
     */
    public VisitDetails() {
        initComponents();
    }
    
        public VisitDetails(String a, String b) {
        initComponents();
        
        memberIDBox.setText(a);
        //memberStatusBox.setText(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        member_ID = new javax.swing.JLabel();
        enter_serviceID = new javax.swing.JTextField();
        service_ID = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enter_comments = new javax.swing.JTextArea();
        visit_comments = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        submit_visit = new javax.swing.JButton();
        memberIDBox = new javax.swing.JTextField();
        ProviderID = new javax.swing.JLabel();
        enterProviderID = new javax.swing.JTextField();
        visit_date = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Visit Details");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        member_ID.setText("Member ID");

        enter_serviceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_serviceIDActionPerformed(evt);
            }
        });

        service_ID.setText("Service ID");

        date_time.setText("Date");

        enter_comments.setColumns(20);
        enter_comments.setRows(5);
        jScrollPane1.setViewportView(enter_comments);

        visit_comments.setText("Comments");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        submit_visit.setText("Submit");
        submit_visit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_visitActionPerformed(evt);
            }
        });

        memberIDBox.setEditable(false);
        memberIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDBoxActionPerformed(evt);
            }
        });

        ProviderID.setText("Provider ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(member_ID)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ProviderID)
                                .addComponent(date_time)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(visit_comments)
                                        .addGap(94, 94, 94))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(enterProviderID, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(memberIDBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(service_ID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enter_serviceID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(visit_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submit_visit)
                                    .addComponent(cancel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member_ID)
                    .addComponent(enter_serviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(service_ID)
                    .addComponent(memberIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProviderID)
                    .addComponent(enterProviderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_time)
                    .addComponent(visit_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(visit_comments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit_visit)
                        .addGap(40, 40, 40)
                        .addComponent(cancel)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
                        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void enter_serviceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_serviceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_serviceIDActionPerformed

    private void submit_visitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_visitActionPerformed
        // TODO add your handling code here:
                DatePicker visit_datevar;
        visit_datevar = visit_date;
        
        //ADD IN TIME SELECTOR

       System.out.println("\n visit_date = " +visit_datevar);
       
       try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chocoloco", "choco", "loco");
            
            String addData = "insert into visits values (?, ?, ? , ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(addData);
            
           // String checkID = "select * from members where memberID = '"+ memberIDBox.getText() +"'";
            //ResultSet id = pstmt.executeQuery(checkID);
            
            //if (id.next()) {
            //    JOptionPane.showMessageDialog(null, "Member ID already exist");
            //}else if (! memberIDBox.getText().matches("[0-9]{9}")) {
            //    JOptionPane.showMessageDialog(null, "Invalid Member ID");
            if (! enter_serviceID.getText().matches("[0-9]{5}")) {
                JOptionPane.showMessageDialog(null, "Invalid Service Code");
            }else if (! enterProviderID.getText().matches("[0-9]{9}")) {
                JOptionPane.showMessageDialog(null, "Invalid Provider Number");
            }
            else {
                pstmt.setInt(1, Integer.parseInt(memberIDBox.getText()));
                pstmt.setString(2, enter_serviceID.getText());
                pstmt.setString(3, enterProviderID.getText());
                pstmt.setDate(4, new java.sql.Date.valueOf(visit_date));
               // Convert.ToDateTime(dateString.ToString)));
                pstmt.setString(5, enter_comments.getText());
            
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Visit Added");
                conn.close();
            
                memberIDBox.setText("");
                enter_serviceID.setText("");
                enterProviderID.setText("");
                visit_date.setText("");
                //visit_time.setText("");
                enter_comments.setText("");
                
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submit_visitActionPerformed

    private void memberIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIDBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProviderID;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel date_time;
    private javax.swing.JTextField enterProviderID;
    private javax.swing.JTextArea enter_comments;
    private javax.swing.JTextField enter_serviceID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField memberIDBox;
    private javax.swing.JLabel member_ID;
    private javax.swing.JLabel service_ID;
    private javax.swing.JButton submit_visit;
    private javax.swing.JLabel visit_comments;
    private com.github.lgooddatepicker.components.DatePicker visit_date;
    // End of variables declaration//GEN-END:variables

    public static DatePicker visit_datevar = null; //global variable for use by app
}
